# Introduction to OpenCV Images Tutorial
This tutorial will go over manipulating images in Opencv, exploring and detailing the structure of the image object and show some examples of simple image tranformations(i.e grayscale and negative conversion). 

In [1]:
import cv2 #OpenCV Library
import numpy #Numerical Python

Again, we import the necessary modules for manipulating images, which is the OpenCV module(cv2) and the numpy module, since we will be modifying the structure of the image(i.e a n-dimensional matrix). Normally, we use the "as" keyword to rename the numpy module to np for less typing in the code (i.e typing np instead of numpy), but for conceptual simplicity, we'll just use numpy in this example.

In [2]:
#image = cv2.imread("/path/to/your/image/file/here/image.jpg")
image = cv2.imread("/home/pinosjxp/Downloads/bird.jpg")

We read in an image file(e.g jpeg, png, ppm, etc..), specified in the path, for use later in the program. The image file's data is stored in a numpy array object that we declared as variable image. This allows us to easily modify the values using numpy operations as we see fit.

In [3]:
print(numpy.shape(image))
print(image)

(478, 717, 3)
[[[ 13  59  46]
  [ 11  61  49]
  [ 12  61  47]
  ..., 
  [162  92 132]
  [163  91 137]
  [162  90 136]]

 [[ 18  57  49]
  [ 16  59  50]
  [ 15  58  49]
  ..., 
  [160  91 136]
  [159  91 138]
  [158  90 137]]

 [[ 18  55  45]
  [ 18  57  42]
  [ 17  55  43]
  ..., 
  [164  92 138]
  [161  92 137]
  [160  91 136]]

 ..., 
 [[ 32 114  85]
  [ 32 114  85]
  [ 25 114  81]
  ..., 
  [ 71 155 121]
  [ 69 153 125]
  [ 69 153 125]]

 [[ 30 115  83]
  [ 29 114  82]
  [ 27 114  80]
  ..., 
  [ 71 155 121]
  [ 70 154 126]
  [ 70 154 126]]

 [[ 30 117  81]
  [ 28 115  81]
  [ 28 116  80]
  ..., 
  [ 68 153 125]
  [ 69 153 124]
  [ 69 153 124]]]


Now we print the shape of the image matrix and the actual matrix of the image so we can see visually see the values  stored in the array. The numpy.shape() function recieves a numpy matrix as a parameter and return the size of each dimension of the matrix as a tuple. In our case, our image is in the BGR format, so we have a three dimensional matrix, with the return tuple containing the height, width, and amount of colors (Should be 3, because blue, green, and red), respectively.

Looking at the results of printing the image matrix to console, we can look at each individual pixel in the image. Referencing above, the first value in the group of three numbers represents the intensity of blue, the second represents green, and the last, red. The values can have a minimun of 0 (Black) and a maximun of 255 (Max saturation of color); the reason for this is that one color value is stored as a byte (8 bits, with a bit being 0 or 1) and 2^8 = 256 different shades of that one color, otherwise known as an unsigned 8-bit integer. We also note the structure of the matrix, which numpy essentialy uses nested lists in order to create the matrix. The colors are grouped into lists of pixels, and the lists of pixels are grouped row by row.

In [4]:
image_negative = numpy.copy(image)
print(image_negative)

[[[ 13  59  46]
  [ 11  61  49]
  [ 12  61  47]
  ..., 
  [162  92 132]
  [163  91 137]
  [162  90 136]]

 [[ 18  57  49]
  [ 16  59  50]
  [ 15  58  49]
  ..., 
  [160  91 136]
  [159  91 138]
  [158  90 137]]

 [[ 18  55  45]
  [ 18  57  42]
  [ 17  55  43]
  ..., 
  [164  92 138]
  [161  92 137]
  [160  91 136]]

 ..., 
 [[ 32 114  85]
  [ 32 114  85]
  [ 25 114  81]
  ..., 
  [ 71 155 121]
  [ 69 153 125]
  [ 69 153 125]]

 [[ 30 115  83]
  [ 29 114  82]
  [ 27 114  80]
  ..., 
  [ 71 155 121]
  [ 70 154 126]
  [ 70 154 126]]

 [[ 30 117  81]
  [ 28 115  81]
  [ 28 116  80]
  ..., 
  [ 68 153 125]
  [ 69 153 124]
  [ 69 153 124]]]


## Negation of an image
Now we will convert the image we read in prior to its negative manualy. Here, an exact copy of the image variable is created and saved to image_grayscale. The print operation shows that the data in image_grayscale is the same as the data in image.

This is the main algorithm that handles the negation of the pixels. It indexes through the matrix row by row and column by column, changes each pixel value to its respective negative value, and saves the result back into the image_negative matrix. Congradulations, the image is now converted to negative. There will be code at the end to display the results but if you can't wait, uncomment the code snippet below to view the image.

In [5]:
for row in image_negative:     # Loops through rows
    for column in row:        # Loops through columns in rows(i.e the pixels)
        column[0]=255-column[0] # Converts Blue value to its negative
        column[1]=255-column[1] # Converts Green value to its negative
        column[2]=255-column[2] # Converts Red value to its negative
print(image_negative)

[[[242 196 209]
  [244 194 206]
  [243 194 208]
  ..., 
  [ 93 163 123]
  [ 92 164 118]
  [ 93 165 119]]

 [[237 198 206]
  [239 196 205]
  [240 197 206]
  ..., 
  [ 95 164 119]
  [ 96 164 117]
  [ 97 165 118]]

 [[237 200 210]
  [237 198 213]
  [238 200 212]
  ..., 
  [ 91 163 117]
  [ 94 163 118]
  [ 95 164 119]]

 ..., 
 [[223 141 170]
  [223 141 170]
  [230 141 174]
  ..., 
  [184 100 134]
  [186 102 130]
  [186 102 130]]

 [[225 140 172]
  [226 141 173]
  [228 141 175]
  ..., 
  [184 100 134]
  [185 101 129]
  [185 101 129]]

 [[225 138 174]
  [227 140 174]
  [227 139 175]
  ..., 
  [187 102 130]
  [186 102 131]
  [186 102 131]]]


In [6]:
# Uncomment this code below if you wish to view the image right now.
#cv2.imshow("Negative Image", image_negative)
#cv2.waitKey(0)

## Grayscale of an image
Another interesting image manipulation is the grayscale operation. There is an openCV function to perform this operation, namely cv2.cvtColor(image, cv2.COLOR_BGR2GRAY), but we will do this manually for practice.

In [7]:
height,width,_ = numpy.shape(image)
image_grayscale = numpy.zeros((height,width),numpy.uint8)
print(image_grayscale)

[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


Here we start by extracting the values from the tuple returned by the numpy.shape() function. Note the undescore placed after the width variable; this essentially means that we are not using the last value in the tuple so ignore the value. Now, since the matrix format for a grayscale image (2-D) is different than that of a color image (3-D), we must create a new matrix that will hold the values for the grayscale conversion. The numpy.zeros() function takes 2 parameters, a tuple of the size of the dimensions of the matrix (i.e a 2x3 matrix would be (2,3), while a 7x14x3 matrix is (7,14,3)) and the datatype of the values stored in the array. The last parameter is optional, but the default value is a floating point number, which is not the same datatype we're using (8 bit unsigned integers), so in our case, we have to add this parameter. The function returns a matrix filled with the number 0.

In [ ]:
for h in range(height):
    for w in range(width):
        #image_grayscale[h][w] = (image[h][w][0]+image[h][w][1]+image[h][w][2])/3
        image_grayscale[h][w] = image[h][w][0]*0.114+image[h][w][1]*0.587+image[h][w][2]*0.299
print(image_grayscale)

[[ 49  51  51 ..., 111 112 111]
 [ 50  51  50 ..., 112 112 111]
 [ 47  48  47 ..., 113 113 112]
 ..., 
 [ 95  95  93 ..., 135 135 135]
 [ 95  94  93 ..., 135 136 136]
 [ 96  94  95 ..., 134 134 134]]


Similar to the negation algorithm, we iterate through every pixel in the original image, row by row, column by column, but now we find the average of all three colors in the pixel and assign that value to its corresponding location in the image_grayscale matrix. The true grayscale operation in commented above, and the difference is correlated to our perception of color; we see more shades of green than any other color, so green is weighted more vesus the other colors.

In [ ]:
cv2.imshow("Original Image",image)
cv2.imshow("Grayscale Image", image_grayscale)
cv2.imshow("Negative Image", image_negative)
cv2.waitKey(0)

Finally, the original, grayscale, and negated images are all displayed so you can visually verify that the algorithms accomplished their objective.